name: integration_test_helper
description: The Integration Test Helper has pre-configured methods that allow for faster test deployment.
version: 0.0.1
homepage: https://github.com/the-mac/integration_test_helper

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
